### ISSUE TITLE
Script analyzer: do not mark using doublequotes as a problem if there are no variables within

### ISSUE THREAD

**Issue by neo42mgn** [neo42-GmbH/PSAppDeployToolKitExtensions#1048]
### Confirmation

- [X] My issue is not related to the behaviour of a package or product provided by neo42
- [X] I understand that issues created in this repository are not subject to any support agreements made with neo42

**Comment by neo42JBR** [comment]
I dont understand the issue. PSScriptAnalyzer does not mark this as an issue. 

It is a formatter setting that converts " to ' if the string does not need to be expanded, making the string a verbatim string.
This may help with readability and in some cases might sligtly increase performance.
