### ISSUE TITLE
Text in AppDeployToolkitConfig.xml are wrong

### ISSUE THREAD

**Issue by HSN42** [neo42-GmbH/PSAppDeployToolKitExtensions#1138]
### Confirmation

- [X] My issue is not related to the behaviour of a package or product provided by neo42
- [X] I understand that issues created in this repository are not subject to any support agreements made with neo42

### Description

Correct the following text:
<NxtWelcomePrompt_ApplicationClose>The **follwing** programs must be closed before the {0} can procced.</NxtWelcomePrompt_ApplicationClose>

correct is following

### Release

2024.09.23.47

**Comment by neo42mgn** [comment]
already implemented
