### ISSUE TITLE
Text in AppDeployToolkitConfig.xml are wrong Bug

### ISSUE THREAD

**Issue by HSN42** [neo42-GmbH/PSAppDeployToolKitExtensions#1172]
### Confirmation

- [X] My issue is not related to the behaviour of a package or product provided by neo42
- [X] I understand that issues created in this repository are not subject to any support agreements made with neo42

### Description

Correct the following text:
<NxtWelcomePrompt_ApplicationClose>The following programs must be closed before the {0} can **procced.**</NxtWelcomePrompt_ApplicationClose>

Correct are:
<NxtWelcomePrompt_ApplicationClose>The following programs must be closed before the {0} can proceed.</NxtWelcomePrompt_ApplicationClose>

### Release

2024.11.27.65

### Architecture

x64, x86

### Deployment System

Matrix42 Empirum (incl. Cloud), Microsoft Intune, Omnissa Workspace One, Microsoft Configuration Manager

**Comment by neo42JBR** [comment]
Will be fixed in #950
